packages:
  - "apps/*"
  - "packages/*"
  - "sdks/*"
  - "sdks/*/samples/*"
  - "products/*/*"
allowBuilds:
  "@swc/core": true
  esbuild: true
minimumReleaseAgeExclude:
  - json-schema-to-typescript@16.0.0
  - '@types/react-dom@19.2.7'
