packages:
  - "apps/*"
  - "packages/*"
  - "sdks/*"
  - "sdks/*/samples/*"
  - "products/*/*"
allowBuilds:
  "@swc/core": true
  esbuild: true
minimumReleaseAgeExclude:
  - json-schema-to-typescript@16.0.0
  - "@types/react-dom@19.2.7"
  - "@ai-sdk/gateway@4.0.78"
  - "@ai-sdk/mcp@2.0.48"
  - "@ai-sdk/provider-utils@5.0.39"
  - "@ai-sdk/provider@4.0.13"
  - "@ai-sdk/react@4.0.100"
  - ai-sdk-ollama@4.3.0
  - ai@7.0.97
