/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DocsProductIndexRouteImport } from './routes/docs.$product.index'
import { Route as DocsProductSlugRouteImport } from './routes/docs.$product.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProductIndexRoute = DocsProductIndexRouteImport.update({
  id: '/$product/',
  path: '/$product/',
  getParentRoute: () => DocsRoute,
} as any)
const DocsProductSlugRoute = DocsProductSlugRouteImport.update({
  id: '/$product/$slug',
  path: '/$product/$slug',
  getParentRoute: () => DocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product/': typeof DocsProductIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product': typeof DocsProductIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRouteWithChildren
  '/docs/': typeof DocsIndexRoute
  '/docs/$product/$slug': typeof DocsProductSlugRoute
  '/docs/$product/': typeof DocsProductIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/docs' | '/docs/' | '/docs/$product/$slug' | '/docs/$product/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/docs/$product/$slug' | '/docs/$product'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/docs/'
    | '/docs/$product/$slug'
    | '/docs/$product/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$product/': {
      id: '/docs/$product/'
      path: '/$product'
      fullPath: '/docs/$product/'
      preLoaderRoute: typeof DocsProductIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/docs/$product/$slug': {
      id: '/docs/$product/$slug'
      path: '/$product/$slug'
      fullPath: '/docs/$product/$slug'
      preLoaderRoute: typeof DocsProductSlugRouteImport
      parentRoute: typeof DocsRoute
    }
  }
}

interface DocsRouteChildren {
  DocsIndexRoute: typeof DocsIndexRoute
  DocsProductSlugRoute: typeof DocsProductSlugRoute
  DocsProductIndexRoute: typeof DocsProductIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsIndexRoute: DocsIndexRoute,
  DocsProductSlugRoute: DocsProductSlugRoute,
  DocsProductIndexRoute: DocsProductIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
